<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BuyerPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyerPaymentRepository extends EntityRepository
{
    public function getPayments($searchArray){

        $start=$searchArray['start'];
        $end=$searchArray['end'];
        $buyer =$searchArray['buyer'];

        $startDate = new \DateTime($start);
        $endDate = new \DateTime($end);
        date_modify($endDate,'+1 day');

        $qb = $this->createQueryBuilder('object');

        if (empty($start)) $start=null;
        if (empty($end)) $end=null;

        //search by buyer
        if (!is_null($buyer))
            $qb->andWhere('object.buyer = :buyer')
                ->setParameter('buyer',$buyer);

        //search by date
        if(!is_null($start) && !is_null($end)){
            $qb->andWhere('object.datetime BETWEEN :startDate AND :endDate')
                ->setParameter('endDate',$endDate)
                ->setParameter('startDate',$startDate);
        }elseif (!is_null($start)){
            $qb->andWhere('object.datetime = :startDate')
                ->setParameter('startDate',$startDate);
        }elseif (!is_null($end)){
            $qb->andWhere('object.datetime <= :endDate')
                ->setParameter('endDate',$endDate);
        }

        $qb->orderBy('object.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
