<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Seller;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    public function getUnconfirmedTransactions(Seller $seller)
    {
        $qb = $this->createQueryBuilder('object');
        $qb->select('object')
            ->where('object.seller = :seller')
            ->andWhere('object.status =  :status')
            ->setParameters(array(
                'seller' => $seller,
                'status' => 1
            ))
            ->orderBy('object.id', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getCompletedTransactions($searchArray){

        $start=$searchArray['start'];
        $end=$searchArray['end'];
        $seller =$searchArray['seller'];

        $startDate = new \DateTime($start);
        $endDate = new \DateTime($end);
        date_modify($endDate,'+1 day');

        if (empty($start)) $start=null;
        if (empty($end)) $end=null;

        $qb = $this->createQueryBuilder('object');
        $qb->select('object')
            ->where('object.status = :status')
            ->setParameter('status',3);

        //search by seller
        if (!is_null($seller))
            $qb->andWhere('object.seller = :seller')
                ->setParameter('seller',$seller);

        //search by date
        if(!is_null($start) && !is_null($end)){
            $qb->andWhere('object.datetime BETWEEN :startDate AND :endDate')
                ->setParameter('endDate',$endDate)
                ->setParameter('startDate',$startDate);
        }elseif (!is_null($start)){
            $qb->andWhere('object.datetime >= :startDate')
                ->setParameter('startDate',$startDate);
        }elseif (!is_null($end)){
            $qb->andWhere('object.datetime <= :endDate')
                ->setParameter('endDate',$endDate);
        }

        $qb->orderBy('object.id', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getBuyerTransactions($searchArray){

        $start=$searchArray['start'];
        $end=$searchArray['end'];
        $buyer =$searchArray['buyer'];

        $startDate = new \DateTime($start);
        $endDate = new \DateTime($end);
        date_modify($endDate,'+1 day');

        if (empty($start)) $start=null;
        if (empty($end)) $end=null;

        $qb = $this->createQueryBuilder('object');
        $qb->select('object')
            ->where('object.status = :status')
            ->setParameter('status',3)
            ->andWhere('object.buyer = :buyer')
            ->setParameter('buyer',$buyer);

        //search by date
        if(!is_null($start) && !is_null($end)){
            $qb->andWhere('object.datetime BETWEEN :startDate AND :endDate')
                ->setParameter('endDate',$endDate)
                ->setParameter('startDate',$startDate);
        }elseif (!is_null($start)){
            $qb->andWhere('object.datetime >= :startDate')
                ->setParameter('startDate',$startDate);
        }elseif (!is_null($end)){
            $qb->andWhere('object.datetime <= :endDate')
                ->setParameter('endDate',$endDate);
        }

        $qb->orderBy('object.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
